### ISSUE TITLE
如何实现相机与雷达的同步？

### ISSUE THREAD

**Issue by laugh12321** [ICEORY/DeepStream#1]
你好，看了你在哔哩哔哩的演示视频，很棒👍。
想知道你是如何实现相机与雷达同步的，是通过时间同步吗？

**Comment by iris0329** [comment]
感谢您对本工作的关注，现在还没有具体的同步代码，目前的视觉上同步的效果是由于传感器自己的接收速度够快。这项功能在开发中，之后可能会继续更新代码。
