### ISSUE TITLE
程序里怎么算调用了SDK，小白求问

### ISSUE THREAD

**Issue by happyEveryDay1005** [ICEORY/DeepStream#2]
livoxSDK和ros driver都安装好了，对于sdk的调用不太理解

**Comment by iris0329** [comment]
Hi, thanks for contact. 

Can you tell me exactly where your problem is according to the README?
Or give a detailed description?

**Comment by happyEveryDay1005** [comment]
I'm sorry to reply you so late. My question is how to import LivoxSDK in the program.

**Comment by iris0329** [comment]
please refer [livox_ros_driver#12-livox-sdk-installation](https://github.com/Livox-SDK/livox_ros_driver#12-livox-sdk-installation) and [README.md](https://github.com/Livox-SDK/Livox-SDK/blob/master/README.md) document to install and run Livox-SDK.
